###
POST http://localhost:3000/users
Content-Type: application/x-www-form-urlencoded

"email": "newemail1@email.com",
"password": "password",
"confirm_password": "password"

###
POST http://localhost:3000/admin
Content-Type: application/x-www-form-urlencoded

"email": "newemail2@email.com",
"password": "password",
"confirm_password": "password"

###
POST http://localhost:3000/neo
Content-Type: application/json

{
  "designation": "2010 PK9",
  "diameter_min": 0.0698081224,
  "diameter_max": 0.156095707,
  "hazardous_asteroid": true,
  "approach_date": "1900-06-01",
  "velocity": 69201.9904887259,
  "miss_distance": 4140648.4089846528,
  "orbiting_body": "Merc"
}
